services:
  flask:
    image: python:3.11-slim
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
